name: Repository Initialization

on:
  push:
    paths:
      - README.md
      - package.json
      - sonar-project.properties

jobs:
  initialize-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace {{repo_name}} in README.md
        env:
          REPO_NAME: ${{ github.repository }}
        run: |
          if [ -f "README.md" ]; then
            sed -i "s/{{repo_name}}/${REPO_NAME##*/}/g" README.md
            echo "README.md file found. Updating."
          else
            echo "README.md file not found. Skipping."
          fi

      - name: Create flag for README.md initialization
        run: echo "Initialized Readme" > .readme-initialized

  initialize-package-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace {{repo_name}} in package.json
        env:
          REPO_NAME: ${{ github.repository }}
        run: |
          if [ -f "package.json" ]; then
            sed -i "s/{{repo_name}}/${REPO_NAME##*/}/g" package.json
            echo "package.json file found. Updating."
          else
            echo "package.json file not found. Skipping."
          fi

      - name: Create flag for package.json initialization
        run: echo "Initialized package.json" > .package-initialized

  initialize-sonar-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace {{repo_name}} in sonar-project.properties
        env:
          REPO_NAME: ${{ github.repository }}
        run: |
          if [ -f "sonar-project.properties" ]; then
            sed -i "s/{{repo_name}}/${REPO_NAME##*/}/g" sonar-project.properties
            echo "sonar-projects.properties file found. Updating."
          else
            echo "sonar-projects.properties file not found. Skipping."
          fi

      - name: Create flag for sonar-project.properties initialization
        run: echo "Initialized sonar-project.properties" > .sonar-initialized

  commit-changes:
    needs: [initialize-readme, initialize-package-json, initialize-sonar-properties]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git pull origin $(git rev-parse --abbrev-ref HEAD) --rebase

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md package.json sonar-project.properties .readme-initialized .package-initialized .sonar-initialized || echo "No changes to commit"
          git commit -m "Initialize repository with repo name" || echo "No changes to commit"
          git push origin $(git rev-parse --abbrev-ref HEAD) || echo "No changes to push"
