name: Initialize Readme

on:
  push:
    paths:
      - sonar-projects.properties  # Trigger only when sonar-projects.properties is added or updated

jobs:
  initialize-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name : Pull latest changes
        run: | 
         git pull origin $(git rev-parse --abbrev-ref HEAD) --rebase      
      - name: Replace {{repo_name}} in sonar-projects.properties
        env:
          REPO_NAME: ${{ github.repository }}
        run: |
          if [ -f "sonar-projects.properties" ]; then
            sed -i "s/{{repo_name}}/${REPO_NAME##*/}/g" sonar-projects.properties
            echo "sonar-projects.properties file found. Updating."
          else
            echo "sonar-projects.properties file not found. Skipping."
          fi
      - name: Create flag file to mark initialization
        run: |
          mkdir -p .github
          echo "Initialized sonar-projects.properties" > .github/.sonar-projects.properties-initialized

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git add sonar-projects.properties .github/.sonar-projects.properties
          git commit -m "Initialize sonar-projects.properties with repo name"
          git push origin $(git rev-parse --abbrev-ref HEAD)
