name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name : Pull latest changes
      run: | 
         git pull origin $(git rev-parse --abbrev-ref HEAD) --no-rebase
         
    - name: Debug Logs
      run: |
        git status
        git log --oneline --graph -10
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install --ignore-engines

    - name: Run ESLint
      run: npm run lint

    - name: Run Prettier check
      run: npm run check-format
      
    - name: Run TypeScript checks
      run: npm run ts-check

    - name: Run tests and generate coverage
      run: npm test -- --coverage

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
